### ISSUE TITLE
Release API to OSSRH staging repository

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jacc#15]
- [ ] Uptake new Eclipse versions of dependencies (if any). Use [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) wiki to find components versions to use.

- [ ] Release to OSSRH staging repository

- [ ] Update [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) with released version number.

**Comment by vinayvishal** [comment]
#16 raised for the changes required before artefacts are pushed to staging repository.

**Comment by vinayvishal** [comment]
It has been released to staging repository. https://oss.sonatype.org/content/groups/staging/jakarta/security/jacc/jakarta.security.jacc-api/1.7/
