### ISSUE TITLE
Update Scope Statement for Jakarta Authorization Contract for Containers Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jacc#24]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by smillidge** [comment]
@arjantijms can you lead and drafting a new scope statement?

**Comment by ivargrimstad** [comment]
Jakarta Authorization Contract for Containers defines the installation and configuration of authorization
providers for use by containers. The specification defines the interfaces that a provider must make available to allow container deployment tools to create and manage permission collections corresponding to roles.

**Comment by smillidge** [comment]
Shouldn't it just be` Jakarta Authorization defines …` given  #25

**Comment by arjantijms** [comment]
@ivargrimstad While the above scope is technically correct, perhaps something like the one below better captures the thing that JACC actually does:

> Jakarta Authorization defines a low-level SPI for authorization modules, which are repositories of permissions facilitating subject based security by determining whether a given subject has a given permission, and algorithms to transform security constraints for specific containers (such as Servlet or EJB) into these permissions.
