### ISSUE TITLE
Prepare Jakarta Authorization for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jacc#30]
### Instructions

- [x] Update text files
- [x] Generate "boilerplate" specification project
- [x] Make a staging release
- [x] Generate Stand-alone TCK test results
- [x] Create a PR to jakartaee/specifications repository
- [x] Update the Jakarta EE API jar by submitting a PR to the [jakartaee-api](https://github.com/eclipse-ee4j/jakartaee-api) project

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by arjantijms** [comment]
Release staged here: https://oss.sonatype.org/content/repositories/staging/jakarta/security/jacc/jakarta.security.jacc-api/1.6.2/

**Comment by arjantijms** [comment]
* [TCK results](https://jenkins.eclipse.org/jacc/job/2_authorization_run_tck_against_staged_build/lastSuccessfulBuild/artifact/jacctck/bin/summary.txt/*view*/)
* [Spec PR 1](https://github.com/jakartaee/specifications/pull/54)
* [Spec PR 2](https://github.com/jakartaee/specifications/pull/55)

Note that the TCK currently fails, but it also fails against a stock GlassFish 5.1.

**Comment by arjantijms** [comment]
TCK now runs:

[TCK results](https://jenkins.eclipse.org/jacc/job/2_authorization_run_tck_against_staged_build/lastSuccessfulBuild/artifact/jacctck/bin/summary.txt/*view*/)

**Comment by arjantijms** [comment]
[API PR](https://github.com/eclipse-ee4j/jakartaee-api/pull/15)

**Comment by arjantijms** [comment]
[Github pages requested](https://bugs.eclipse.org/bugs/show_bug.cgi?id=549720)
