### ISSUE TITLE
Compatibility certification request for EE4J implementation of Jakarta Authorization

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jacc#46]
- [x] Organization Name ("Organization") and, if applicable, URL
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)
  [Eclipse GlassFish 5.1](https://www.eclipse.org/downloads/download.php?file=/glassfish/glassfish-5.1.0.zip)
- [x] Specification Name, Version and download URL
  [Jakarta Authorization, 1.5](https://jakarta.ee/specifications/authorization/1.6/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL
  [Jakarta Authorization TCK 1.5.0](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/promoted/eclipse-authorization-tck-1.5.0.zip), SHA-256: `81373a045b7bb187989eafbf6c4be5b6f7f28d25cdbdae03e2fcf343889f77f2`
- [x] Public URL of TCK Results Summary
  [TCK results summary](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-authorization/1.5/TCK-Results.html)
- [x] Any Additional Specification Certification Requirements
  None
- [x] Java runtime used to run the implementation
  Oracle JDK 1.8.0_191
- [x] Summary of the information for the certification environment, operating system, cloud, ...
  Linux Centos 7
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by scottmarlow** [comment]
@arjantijms [Java EE 8](https://javaee.github.io/tutorial/overview008.html) seems to reference JACC 1.5, not 1.6.  Are the JACC 1.6 API class signatures that same as JACC 1.5?  

It also looks like the Jakarta EE 8 platform TCK is still referring to JACC as 1.5, in [javax.security.jacc.sig_1.5_se8](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/signaturetest/signature-repository/javax.security.jacc.sig_1.5_se8).  I don't see javax.security.jacc.sig_1.6_se8

**Comment by arjantijms** [comment]
@scottmarlow There's a version confusion that started when Oracle released the API for the JACC 1.5 spec as 1.6: https://mvnrepository.com/artifact/javax.security.jacc/javax.security.jacc-api/1.6

There was a discussion at the spec committee call today about this, as well as a discussion on the mailinglist `[jakarta.ee-spec.committee] JACC Version Number Issue`

We need to establish what we set as the right version going forward, but it's not trivial as artefacts have already been released to Maven central.

**Comment by arjantijms** [comment]
Closing this as it's piggy-backing on the GlassFish CR.

**Comment by arjantijms** [comment]
As project lead I assert this can be marked accepted and closed.
