### ISSUE TITLE
Build CI/CD pipeline 

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jacc#6]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by arjantijms** [comment]
Project CI environment has been requested:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=538666

**Comment by m0mus** [comment]
Update from @arjantijms:

Two jobs created. 
Simple maven job for master builds - succeeds
Release job based on shell script and using secret files; needs updating of pom in EE4J_* branch still.

Closing this task as completed based on the status above.
