### ISSUE TITLE
Release pipeline and first release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jacc#7]
We need to create a release CI/CD pipeline for this project and release the first version from Eclipse. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)

**Comment by m0mus** [comment]
Update from @arjantijms:
```
Simple maven job for master builds - succeeds
Release job based on shell script and using secret files; needs updating of pom in EE4J_* branch still.
```

**Comment by arjantijms** [comment]
pom updated, and release job updated as well. Branch https://github.com/eclipse-ee4j/jacc/tree/1.7 is created by jacc-bot.
